theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_statusbar_location: bottom
plugins:
  - fullscreen
theme_advanced_disable :
  - help
  - image
  - styleselect
  - search
  - replace
  - pastetext
  - pasteword
  - help
  - code
  - insertdate
  - inserttime
  - forecolor
  - backcolor
  - sub
  - sup




